server:
    port: 8080
    
spring:
    application:
        name: microsservices
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                use_sql_comments: true
                jdbc:
                    time_zone: UTC