services:

  db:
    image: mysql    
    ports:
      - "3306:3306"
    environment:      
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                
    volumes: 
      - microservicos:/var/lib/mysql

volumes:
  microservicos:
    

